name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config
        export KUBECONFIG=~/.kube/config

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install project dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install flake8

    - name: Log in to registry.dp.tech
      uses: docker/login-action@v3
      with:
        registry: registry.dp.tech
        username: dplc@dptech
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & deploy all tools
      run: |
        for dir in servers/*/; do
          tool=$(basename "$dir")

          echo "🔨 Building $tool"
          python hack/build_docker.py "$tool"

          echo "⚙️ Generating k8s config for $tool"
          python hack/gen_k8s.py "$tool" 50001

          tool_lower=$(echo "$tool" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
          echo "✅ Validating k8s configs for $tool_lower"
          kubectl --dry-run=client apply -f "infra/k8s/$tool_lower/" || true

          echo "🚀 Deploying $tool_lower to Kubernetes"
          kubectl apply -f "infra/k8s/$tool_lower/"
        done