name: CI

on:
  push:          # 对 main / master 任何 push
    branches: [ main, master ]
  pull_request:  # PR 目标为 main / master
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Detect modified tools
      id: filter
      uses: dorny/paths-filter@v3
      with:
        token: ${{ github.token }}
        list-files: shell
        filters: |
          tools-changed:
            - added|modified: 'servers/*/**'

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config
        export KUBECONFIG=~/.kube/config

    - name: Skip when nothing to build
      if: steps.filter.outputs.tools-changed == 'false'
      run: echo "No tools changed – skipping build & test."

    - name: Set up Python 3.12
      if: steps.filter.outputs.tools-changed == 'true'
      uses: actions/setup-python@v4
      with: {python-version: '3.12'}

    - name: Install project dependencies
      if: steps.filter.outputs.tools-changed == 'true'
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install flake8

    - name: Log in to registry.dp.tech
      uses: docker/login-action@v3
      with:
        registry: registry.dp.tech
        username: dplc@dptech
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & test changed tools
      if: steps.filter.outputs.tools-changed == 'true'
      run: |
        declare -A changed=()
        for f in ${{ steps.filter.outputs.tools-changed_files }}; do
          tool=$(echo "$f" | cut -d/ -f2)
          changed["$tool"]=1
        done

        echo "Tools to build: ${!changed[@]}"
        for t in "${!changed[@]}"; do
          echo "🔨 Building $t"
          python hack/build_docker.py "$t"
          
          echo "⚙️ Generating k8s config for $t"
          python hack/gen_k8s.py "$t" 50001
          
          # 验证生成的k8s配置语法
          tool_lower=$(echo "$t" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
          echo "✅ Validating k8s configs for $tool_lower"
          kubectl --dry-run=client apply -f "infra/k8s/$tool_lower/" || true
        done

    - name: Deploy to Kubernetes
      if: steps.filter.outputs.tools-changed == 'true' && github.ref == 'refs/heads/main'
      run: |
        declare -A changed=()
        for f in ${{ steps.filter.outputs.tools-changed_files }}; do
          tool=$(echo "$f" | cut -d/ -f2)
          changed["$tool"]=1
        done

        for t in "${!changed[@]}"; do
          tool_lower=$(echo "$t" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
          echo "🚀 Deploying $t to Kubernetes"
          kubectl apply -f "infra/k8s/$tool_lower/"
        done