name: Release

on:
  push:
    tags: [ 'v*' ]     # 例如 v1.2.3

permissions:
  contents: read       # 读仓库
  packages: write      # 推 GHCR

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: {fetch-depth: 0}   # 需要完整 git 历史

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ---------- ① 找上一个 tag ----------
    - id: prev
      run: |
        last=$(git describe --tags --abbrev=0 $(git rev-parse HEAD^) 2>/dev/null || echo '')
        echo "last=$last" >> $GITHUB_OUTPUT

    - name: Build + push ALL tools
      env:
        TAG: ${{ github.ref_name }}   # vX.Y.Z
      run: |
        for dir in servers/*/; do
          tool=$(basename "$dir")
          echo "🚀 Building $tool with tag $TAG"
          python hack/build_docker.py "$tool" --tag "$TAG" --push
          python hack/gen_k8s.py "$tool" 50001
        done

    # ---------- ③ 创建 GitHub Release ----------
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true

    # ---------- ④ 创建 GitHub Release ----------
    - name: Create GitHub Release
      if: steps.new.outputs.dirs != ''
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true